### ISSUE TITLE
[Enhancement] Possible to work on author pages

### ISSUE THREAD

**Issue by arogl** [harshankur/defaultAmazonSort#1]
[J.S Donovan Author page](https://www.amazon.com/stores/J.S.-Donovan/author/B01J6FHKU2?ref=ap_rdr&store_ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true)

This defaults to Popularity, can it be changed to the order as set by this extension.

Also on this page is a [See All](https://www.amazon.com/stores/J.S.-Donovan/author/B01J6FHKU2/allbooks?ref=ap_rdr&store_ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true) link, is it possible to set that as well?

**Comment by harshankur** [comment]
Sorry for the delay in responding.
I have looked at the possibility of adding this feature. However, Amazon websites are not consistent across the world. Author pages in the US are very different from, say, India. Moreover, the page structures seem to be different for a few authors even on the US website. It would be a hit-and-miss for most cases. Further, there are very few identifiers on their website for me to work on to select the desired default sorting option.

I am sorry I could not be of help in this. 😕
